// GENERATED BY scripts/make-slideshows.sh -- DO NOT EDIT BY HAND.
// Add or remove photos in pics/slideshowN/, then re-run that script.
var SLIDESHOWS = {
  "slideshow1": ["andy-1.jpeg", "andy-d-1.jpeg", "boris-karolis-1.jpeg", "karolis-d-1.jpeg", "lucy-1.jpeg", "math-boris.jpg"],
  "slideshow2": ["boris-stacey-1.jpeg", "kieran.jpg", "matt-boris-reg.jpg", "richf-1.jpeg", "stacey-yaniv-bryna-1.jpeg", "yaniv-1.jpeg"],
  "slideshow3": ["carrie.jpg", "david.jpg", "deren.jpg", "math-1.jpg", "richg-2.jpeg", "wallace-m.jpg"],
  "slideshow4": ["andy-karolis-1.jpeg", "boris-rich-3.jpeg", "boris-ur-1.jpeg", "brit.jpg", "emir.jpg", "jesse.jpg"],
  "slideshow5": ["boris-courtney-1.jpeg", "boris-leather.jpg", "boris-luke-1.jpeg", "boris-phils-1.jpeg", "foursome-1.jpeg", "math-2.jpg"],
  "slideshow6": ["alexa-1.jpg", "andy-l-1.jpeg", "boris-loza-1.jpeg", "christie-ul-2.jpeg", "danielle-2.jpeg", "darwin-r.jpg", "grace-brit.jpg", "lora.jpg"],
  "slideshow7": ["alexa-2.jpg", "boris-2.jpeg", "emma-1.jpeg", "matt-boris-shock.jpg", "natalie-kieran.jpg", "richf-2.jpeg", "sally.jpg"],
  "slideshow8": ["alexa-grace.jpg", "andy-karolis-1.jpeg", "boris-jeff.jpg", "karolis-u-1.jpeg", "tanjona-1.jpeg", "walter-emma.jpg"],
  "slideshow9": ["boris-3.jpeg", "bryna-boris.jpg", "emma-ul-1.jpeg", "grace-kieran.jpg"]
};
