// GENERATED BY scripts/make-slideshows.sh -- DO NOT EDIT BY HAND.
// Add or remove photos in pics/slideshowN/, then re-run that script.
var SLIDESHOWS = {
  "slideshow1": ["andy-1.jpeg", "andy-d-1.jpeg", "karolis-br-1.jpeg", "karolis-d-1.jpeg", "lucy-1.jpeg"],
  "slideshow2": ["boris-andy-1.jpeg", "boris-karolis-1.jpeg", "richf-1.jpeg", "stacey-1.jpeg", "stacey-yaniv-bryna-1.jpeg", "yaniv-1.jpeg"],
  "slideshow3": ["boris-stacey-1.jpeg", "richg-2.jpeg", "wallace-m.jpg"],
  "slideshow4": ["andy-karolis-1.jpeg", "boris-loza-1.jpeg", "boris-rich-3.jpeg", "boris-ur-1.jpeg"],
  "slideshow5": ["boris-courtney-1.jpeg", "boris-luke-1.jpeg", "boris-phils-1.jpeg", "foursome-1.jpeg"],
  "slideshow6": ["christie-l-1.jpeg", "christie-ul-2.jpeg", "danielle-2.jpeg", "darwin-r.jpg"],
  "slideshow7": ["boris-2.jpeg", "emma-1.jpeg", "emma-ur-1.jpeg", "richf-2.jpeg"],
  "slideshow8": ["andy-karolis-1.jpeg", "karolis-u-1.jpeg", "tanjona-1.jpeg"],
  "slideshow9": ["andy-l-1.jpeg", "andy-ul-1.jpeg", "boris-3.jpeg", "emma-ul-1.jpeg"]
};
