#!/bin/bash
#
# Regenerates pics/slideshows.js, the manifest that index.html uses to fill the
# 3x3 photogrid.  Every .jpg/.jpeg found in pics/slideshow1 ... pics/slideshow9
# is listed, in alphabetical order.
#
# To add or remove a photo: drop it into (or delete it from) the relevant
# pics/slideshowN folder, then run this script and commit the result.
#
#     ./scripts/make-slideshows.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."
out=pics/slideshows.js

{
    echo "// GENERATED BY scripts/make-slideshows.sh -- DO NOT EDIT BY HAND."
    echo "// Add or remove photos in pics/slideshowN/, then re-run that script."
    echo "var SLIDESHOWS = {"
    for i in 1 2 3 4 5 6 7 8 9; do
        dir="pics/slideshow$i"
        printf '  "slideshow%d": [' "$i"
        sep=""
        if [ -d "$dir" ]; then
            while IFS= read -r f; do
                printf '%s"%s"' "$sep" "$(basename "$f")"
                sep=", "
            done < <(find "$dir" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' \) | LC_ALL=C sort)
        fi
        if [ "$i" -lt 9 ]; then echo "],"; else echo "]"; fi
    done
    echo "};"
} > "$out"

echo "wrote $out"
